apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sftp-server
  template:
    metadata:
      labels:
        app: sftp-server
    spec:
      containers:
        - name: sftp-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 22
        {{ if .Values.persistence.enabled }}
          volumeMounts:
            - name: {{ .Values.persistence.storageName }}
              mountPath: /home
        {{- end}}
    {{ if .Values.persistence.enabled }}
      volumes:
        - name: {{ .Values.persistence.storageName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.storageName }}
            storageClassName: {{ .Values.persistence.storageClassName }}
            storage: {{ .Values.persistence.storageSize }}
    {{ end }}

