apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.storageName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
    storageClassName: {{ .Values.persistence.storageClassName }}
