apiVersion: v1
kind: Service
metadata:
  name: sftp-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22
  selector:
    app: sftp-server
